backend/apps/library/urls.py
# urls.py
from django.conf.urls import url

from apps.library.views import UserLibraryCreate
from apps.library.views import UserLibraryList
from apps.library.views import UserLibraryListApi
from apps.library.views import BookCreate
from apps.library.views import BookList
from apps.library.views import BookListApi
from apps.library.views import BorrowingCreate
from apps.library.views import BorrowingList
from apps.library.views import Index

urlpatterns = [
    url(r'new-user/$', UserLibraryCreate.as_view(), name='new-user'),
    url(r'new-book/$', BookCreate.as_view(), name='new-book'),
    url(r'users/$', UserLibraryList.as_view(), name='users-list'),
    url(r'books/$', BookList.as_view(), name='books-list'),
    url(r'users-api/$', UserLibraryListApi.as_view(), name='users-list-api'),
    url(r'books-api/$', BookListApi.as_view(), name='books-list-api'),
    url(r'new-borrowing/$', BorrowingCreate.as_view(), name='new-borrowing'),
    url(r'borrowings/$', BorrowingList.as_view(), name='borrowings-list'),
    url(r'dashboard/$', Index.as_view(), name='dashboard'),

]

backend/backend/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^library/', include('apps.library.urls', namespace='library')),
]

backend/apps/core/models.py
from django.db import models

# Create your models here.

backend/apps/library/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse


class UserLibrary(models.Model):

    name = models.CharField(_('Nome'), max_length=50, blank=False, null=False,
                            unique=True)
    # author TODO  with unique together with name

    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Users"

    def __str__(self):
        return "{} - {}".format(self.id, self.name)

    def get_absolute_url(self):
        return reverse('library:users-list')


class Book(models.Model):
    name = models.CharField(_('Nome'), max_length=50, blank=False, null=False,
                            unique=True)
    is_borrowed = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Livro"
        verbose_name_plural = "Books"

    def __str__(self):
        return "{} - {}".format(self.id, self.name)

    def get_absolute_url(self):
        return reverse('library:books-list')


class Borrowing(models.Model):
    book = models.ForeignKey(Book)
    user = models.ForeignKey(UserLibrary)

    initial_date = models.DateTimeField(auto_now_add=True, blank=False,
                                        null=False)
    finish_date = models.DateTimeField(blank=False, null=True)

    class Meta:
        verbose_name = "Empréstimo"
        verbose_name_plural = "Borrowings"

    def __str__(self):
        return "{} - {} - {}".format(self.book, self.user, '')

    def get_absolute_url(self):
        return reverse('library:borrowings-list')

backend/apps/library/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from apps.library.models import UserLibrary
from apps.library.models import Book
from apps.library.models import Borrowing


class UserLibraryForm(ModelForm):
    name = forms.CharField(label=("Nome"),
                           widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = UserLibrary
        fields = ['name']


class BookForm(ModelForm):
    name = forms.CharField(label=("Nome"),
                           widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Book
        fields = ['name']


class BorrowingForm(ModelForm):
    book = forms.ModelChoiceField(queryset=Book.objects.all(), label=("Selecione o livro"),
                                  widget=forms.Select(attrs={'class': 'form-control'}))
    user = forms.ModelChoiceField(queryset=UserLibrary.objects.all(), label=("Selecione o usuário"),
                                  widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Borrowing
        fields = ['book', 'user']

    def clean_book(self):
        book = self.cleaned_data['book']

        if book.is_borrowed:
            raise forms.ValidationError("Livro indisponível.")

        return book

backend/apps/core/views.py
from django.shortcuts import render

# Create your views here.

backend/apps/library/views.py
# -*- coding: utf-8 -*-


from django.views.generic import TemplateView
from django.contrib.messages.views import SuccessMessageMixin

from django.views.generic import ListView
from django.views.generic.edit import CreateView

from apps.library.models import UserLibrary
from apps.library.models import Book
from apps.library.models import Borrowing
from apps.library.forms import UserLibraryForm
from apps.library.forms import BookForm
from apps.library.forms import BorrowingForm
from apps.library.serializers import UserLibrarySerializer
from apps.library.serializers import BookSerializer
from rest_framework.generics import ListAPIView
from rest_framework.renderers import JSONRenderer


class Index(TemplateView):
    template_name = "library/index.html"

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['title'] = context['pageHeader'] = "Dashboard"
        context['showBtnBack'] = False
        return context


class UserLibraryCreate(SuccessMessageMixin, CreateView):
    model = UserLibrary
    form_class = UserLibraryForm
    success_message = "%(name)s foi criado com sucesso."

    def get_context_data(self, **kwargs):
        context = super(UserLibraryCreate, self).get_context_data(**kwargs)
        context['title'] = context['pageHeader'] = "Novo usuário"
        context['showBtnBack'] = True
        return context


class UserLibraryList(ListView):
    model = UserLibrary
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(UserLibraryList, self).get_context_data(**kwargs)
        context['title'] = context['pageHeader'] = "Lista de usuários"
        context['showBtnBack'] = True
        return context


class UserLibraryListApi(ListAPIView):
    renderer_classes = (JSONRenderer, )
    queryset = UserLibrary.objects.all()
    serializer_class = UserLibrarySerializer


class BookListApi(ListAPIView):
    renderer_classes = (JSONRenderer, )
    queryset = Book.objects.all()
    serializer_class = BookSerializer


class BookCreate(SuccessMessageMixin, CreateView):
    model = Book
    form_class = BookForm
    success_message = "%(name)s foi criado com sucesso."

    def get_context_data(self, **kwargs):
        context = super(BookCreate, self).get_context_data(**kwargs)
        context['title'] = context['pageHeader'] = "Novo livro"
        context['showBtnBack'] = True
        return context


class BookList(ListView):
    model = Book
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(BookList, self).get_context_data(**kwargs)
        context['title'] = context['pageHeader'] = "Lista de livros"
        context['showBtnBack'] = True
        return context


class BorrowingCreate(CreateView):
    model = Borrowing
    form_class = BorrowingForm

    success_message = "O empréstimo foi criado com sucesso."

    def form_valid(self, form):
        self.object = form.save()
        self.object.book.is_borrowed = True
        self.object.book.save()
        return super(BorrowingCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(BorrowingCreate, self).get_context_data(**kwargs)
        context['title'] = context['pageHeader'] = "Empréstimos de livro"
        context['showBtnBack'] = True
        return context


class BorrowingList(ListView):
    model = Borrowing
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(BorrowingList, self).get_context_data(**kwargs)
        context['title'] = context['pageHeader'] = "Lista de empréstimos"
        context['showBtnBack'] = True
        return context

backend/apps/core/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{title}}</title>
    <link rel="stylesheet" href="">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"
  integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E="
  crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
</head>
<body>
<div class="container">
<div class="page-header">
    {%if showBtnBack %}
    <div class="row">
        <div class="col-md-2"><a href="{% url 'library:dashboard' %}" type="button" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>Voltar</a></div>
        <div class="col-md-10"><h1>{{pageHeader}}</h1></div>
    </div>
    {%else%}
<h1>{{pageHeader}}</h1>
{%endif%}


  <!-- {%block pageHeader%}{%endblock pageHeader%} -->
</div>

{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success" role="alert">{{message}}</div>
        {% endif %}
    {% endfor %}
{% endif %}

{%block content%}
{%endblock content%}
</div>

</body>
</html>

backend/apps/core/templates/snippets/pagination.html
{% if is_paginated %}
  <nav >
  <ul class="pager">
    {% if page_obj.has_previous %}
        <li class="previous"><a href="?page={{ page_obj.previous_page_number }}"><span aria-hidden="true">&larr;</span> Anterior</a></li>
      {% else %}
          <li class="previous disabled"><a href="#"><span aria-hidden="true">&larr;</span> Anterior</a></li>
      {% endif %}

    {% if page_obj.has_next %}
      <li class="next"><a href="?page={{ page_obj.next_page_number }}">Próximo <span aria-hidden="true">&rarr;</span></a></li>
    {% else %}
    <li class="next disabled"><a href="#">Próximo<span aria-hidden="true">&rarr;</span></a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}

backend/apps/library/templates/library/book_form.html
{%extends 'base.html'%}


{%block content%}
<form action="" method="post">{% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {# Include the visible fields #}
    {% for field in form.visible_fields %}
        <div class="form-group {%if field.errors|length > 0%}has-error{%endif%}">
            {% if field.errors  %}
                {% for error in field.errors %}
                    <div class="alert alert-danger"><strong>{{ error|escape }}</strong></div>
                {% endfor %}
            {% endif %}
            {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}

    <button type="submit" class="btn btn-default">Registrar no sistema</button>
</form>
{%endblock content%}

backend/apps/library/templates/library/book_list.html
{% extends "base.html" %}
{%block pageHeader%}<span style="float:right"> TODO INPUT TO SEARCH</span>{%endblock pageHeader%}
{%block content%}
<a href="{% url 'library:new-book' %}" type="button" class="btn btn-default" style="margin-bottom:20px">Criar novo livro</a>
{%if object_list%}
<table class="table table-striped table-bordered">
  <thead>
      <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Emprestado</th>
    </tr>
  </thead>
  <tbody>
    {% for userLibrary in object_list %}
        <tr>
          <td>{{userLibrary.id}}</td>
          <td>{{userLibrary.name}}</td>
          <td>{%if userLibrary.is_borrowed%}Sim{%else%}Não{%endif%}</td>
        </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<div class="alert alert-info" role="alert">Você não possui livros cadastrados.</div>
{%endif%}
{% include 'snippets/pagination.html' %}
{%endblock content%}

backend/apps/library/templates/library/borrowing_form.html
{%extends 'base.html'%} {%block content%}

<form action="" method="post">{% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
        <div class="form-group {%if field.errors|length > 0%}has-error{%endif%}">
            {% if field.errors  %}
                {% for error in field.errors %}
                    <div class="alert alert-danger"><strong>{{ error|escape }}</strong></div>
                {% endfor %}
            {% endif %}
            {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}

    <button type="submit" class="btn btn-default">Registrar no sistema</button>
</form>
<!-- <script>
$(function() {
    $("#id_book").autocomplete({
        source: function(request, response) {
            $.ajax({
                url: "{% url 'library:books-list-api' %}",
                data: { query: request.term },
                success: function(data) {
                    var transformed = $.map(data, function(el) {
                        return {
                            label: el.name,
                            id: el.id
                        };
                    });
                    response(transformed);
                },
                error: function() {
                    response([]);
                }
            });
        }
    });
    $("#id_user").autocomplete({
        source: function(request, response) {
            $.ajax({
                url: "{% url 'library:users-list-api' %}",
                data: { query: request.term },
                success: function(data) {
                    var transformed = $.map(data, function(el) {
                        return {
                            label: el.name,
                            id: e.id
                        };
                    });
                    response(transformed);
                },
                error: function() {
                    response([]);
                }
            });
        }
    });
});
</script> -->
{%endblock content%}

backend/apps/library/templates/library/borrowing_list.html
{% extends "base.html" %}
{%block pageHeader%}<span style="float:right"> TODO INPUT TO SEARCH</span>{%endblock pageHeader%}
{%block content%}
<a href="{% url 'library:new-borrowing' %}" type="button" class="btn btn-default" style="margin-bottom:20px">Criar novo empréstimo</a>
{%if object_list%}
<table class="table table-striped table-bordered">
  <thead>
      <tr>
        <th>Código</th>
        <th>Livro</th>
        <th>Usuario</th>
    </tr>
  </thead>
  <tbody>
    {% for borrowing in object_list %}
        <tr>
          <td>{{borrowing.id}}</td>
          <td>{{borrowing.book}}</td>
          <td>{{borrowing.user}}</td>
        </tr>
    {% endfor %}
  </tbody>
</table>
{%else%}
<div class="alert alert-info" role="alert">Você não possui empréstimos cadastrados.</div>
{%endif%}
{% include 'snippets/pagination.html' %}
{%endblock content%}

backend/apps/library/templates/library/index.html
{%extends 'base.html'%}


{%block content%}
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Usuários</h3>
            </div>
            <div class="panel-body">
                <a type="button" href="{%url 'library:users-list' %}" class="btn btn-primary btn-block">Manipule os usuários</a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Livros</h3>
            </div>
            <div class="panel-body">
                <a type="button" href="{%url 'library:books-list' %}" class="btn btn-primary btn-block">Manipule os livros</a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Empréstimos</h3>
            </div>
            <div class="panel-body">
                <a type="button" href="{%url 'library:borrowings-list' %}" class="btn btn-primary btn-block">Manipule os empréstimos</a>

            </div>
        </div>
    </div>
</div>
{%endblock content%}

backend/apps/library/templates/library/userlibrary_form.html
{%extends 'base.html'%}


{%block content%}
<form action="" method="post">{% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {# Include the visible fields #}
    {% for field in form.visible_fields %}
        <div class="form-group {%if field.errors|length > 0%}has-error{%endif%}">
            {% if field.errors  %}
                {% for error in field.errors %}
                    <div class="alert alert-danger"><strong>{{ error|escape }}</strong></div>
                {% endfor %}
            {% endif %}
            {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}

    <button type="submit" class="btn btn-default">Registrar no sistema</button>
</form>
{%endblock content%}

backend/apps/library/templates/library/userlibrary_list.html
{% extends "base.html" %}
{%block pageHeader%}<span style="float:right"> TODO INPUT TO SEARCH</span>{%endblock pageHeader%}
{%block content%}
<a href="{% url 'library:new-user' %}" type="button" class="btn btn-default" style="margin-bottom:20px">Criar novo usuário</a>
{%if object_list%}
<table class="table table-striped table-bordered">
  <thead>
      <tr>
        <th>Código</th>
        <th>Nome</th>
    </tr>
  </thead>
  <tbody>
    {% for userLibrary in object_list %}
        <tr>
          <td>{{userLibrary.id}}</td>
          <td>{{userLibrary.name}}</td>
        </tr>
    {% endfor %}
  </tbody>
</table>
{%else%}
    <div class="alert alert-info" role="alert">Você não possui usuários cadastrados.</div>
{%endif%}
{% include 'snippets/pagination.html' %}
{%endblock content%}